domain: nhsengland.github.io
url: https://nhsengland.github.io
baseurl: /DataScience-ReusableCode
repository: nhsengland/DataScience-ReusableCode
title: Reusable Code
description: Pointers to our code developed for reuse
email: datascience@nhs.net
github_username: nhsengland
plugins:
  - jemoji

